import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";

import { Header } from "@/components/header";
import Footer from "@/components/footer";
import { SideMenu } from "@/components/side-menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`antialiased notranslate ${geistMono.variable} ${geistSans.variable}`}
      translate="no"
      suppressHydrationWarning
    >
      <body
        className={
          "relative min-h-screen font-mono flex flex-col justify-between"
        }
      >
        <div className={"flex-1"}>
          <Header />
          <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 bg-muted/20 py-4 md:gap-8 md:py-10">
            <div className="container mx-auto space-y-8 lg:space-y-12">
              <div className="mx-auto grid w-full items-start gap-6 lg:grid-cols-[250px_1fr]">
                <nav className="hidden lg:grid gap-2 text-sm sticky top-[100px]">
                  <SideMenu />
                </nav>
                <div className="flex-1 space-y-8 lg:space-y-12">{children}</div>
              </div>
            </div>
          </main>
        </div>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1170295433759824"
          crossOrigin="anonymous"
        />
        <Footer />
      </body>
    </html>
  );
}
